package com.appchat.entity.user.enums.permission;

import java.io.Serializable;

public enum PermissionValues implements Serializable {
    LINE_OUTPUT,
    DEPARTMENT_MODERATION,
    CREATE_GROUP_CHATS,
    ROLES_MODERATION,
    BAN_LIST_MODERATION,
    MESSAGES_TEMPLATE_MODERATION,
    SERVICE_REQUEST_MODERATION,
    REGISTRATION_EMPLOYEES,
    IMPORT_EMPLOYEES,
    EDITING_PROFILES_EMPLOYEE,
    VIEW_ALL_EMPLOYEES,
    BAN_EMPLOYEES,
    DELETE_EMPLOYEES,
    RESETTING_PASSWORD_EMPLOYEES,
    CHANGING_ROLES_EMPLOYEE,
    CHANGING_PERMISSIONS_EMPLOYEE,
    DEPARTMENT_MANAGEMENT_EMPLOYEES,
    REGISTRATION_CUSTOMER,
    EDITING_CUSTOMER,
    IMPORTING_CUSTOMERS,
    BAN_CUSTOMER,
    DELETE_CUSTOMER,
    AUTHORIZATION_METHOD_CUSTOMER,
    ACCESS_DATA_CUSTOMERS,
    VIEW_ALL_CUSTOMERS,
    VIEW_ALL_MESSAGES_CUSTOMERS,
    DATA_EXPORT_CUSTOMER,
    TECHNICAL_INFORMATION_CUSTOMERS,
    SCHEDULE_SETTING,
    CREATING_MAILING_LIST_CUSTOMERS,
    CREATING_MAILING_LIST_EMPLOYEES
}
