-- liquibase formatted sql

-- changeset kuchart:1669647372218-41

INSERT INTO "role" (deleted, permission_list, role_name, description)
values (false,
        'LINE_OUTPUT;DEPARTMENT_MODERATION;CREATE_GROUP_CHATS;ROLES_MODERATION;BAN_LIST_MODERATION;MESSAGES_TEMPLATE_MODERATION;SERVICE_REQUEST_MODERATION;REGISTRATION_EMPLOYEES;IMPORT_EMPLOYEES;EDITING_PROFILES_EMPLOYEE;VIEW_ALL_EMPLOYEES;BAN_EMPLOYEES;DELETE_EMPLOYEES;RESETTING_PASSWORD_EMPLOYEES;CHANGING_ROLES_EMPLOYEE;CHANGING_PERMISSIONS_EMPLOYEE;DEPARTMENT_MANAGEMENT_EMPLOYEES;REGISTRATION_CUSTOMER;EDITING_CUSTOMER;IMPORTING_CUSTOMERS;BAN_CUSTOMER;DELETE_CUSTOMER;AUTHORIZATION_METHOD_CUSTOMER;ACCESS_DATA_CUSTOMERS;VIEW_ALL_CUSTOMERS;VIEW_ALL_MESSAGES_CUSTOMERS;DATA_EXPORT_CUSTOMER;TECHNICAL_INFORMATION_CUSTOMERS;SCHEDULE_SETTING;CREATING_MAILING_LIST_CUSTOMERS;CREATING_MAILING_LIST_EMPLOYEES',
        'Глобальный администратор', 'Доступны все действия, кроме чтения чатов в которых он отсутствует');

INSERT INTO user_type(type_name, description, in_use)
values ('WORKER', 'WORKER TYPE', true),
       ('CLIENT', 'CLIENT TYPE', true);

INSERT INTO "user" (deleted, banned, extended_permission_list, "enabled", user_type, birth_date, first_name, last_name)
values (false, false,
        'LINE_OUTPUT;DEPARTMENT_MODERATION;CREATE_GROUP_CHATS;ROLES_MODERATION;BAN_LIST_MODERATION;MESSAGES_TEMPLATE_MODERATION;SERVICE_REQUEST_MODERATION;REGISTRATION_EMPLOYEES;IMPORT_EMPLOYEES;EDITING_PROFILES_EMPLOYEE;VIEW_ALL_EMPLOYEES;BAN_EMPLOYEES;DELETE_EMPLOYEES;RESETTING_PASSWORD_EMPLOYEES;CHANGING_ROLES_EMPLOYEE;CHANGING_PERMISSIONS_EMPLOYEE;DEPARTMENT_MANAGEMENT_EMPLOYEES;REGISTRATION_CUSTOMER;EDITING_CUSTOMER;IMPORTING_CUSTOMERS;BAN_CUSTOMER;DELETE_CUSTOMER;AUTHORIZATION_METHOD_CUSTOMER;ACCESS_DATA_CUSTOMERS;VIEW_ALL_CUSTOMERS;VIEW_ALL_MESSAGES_CUSTOMERS;DATA_EXPORT_CUSTOMER;TECHNICAL_INFORMATION_CUSTOMERS;SCHEDULE_SETTING;CREATING_MAILING_LIST_CUSTOMERS;CREATING_MAILING_LIST_EMPLOYEES',
        true, 1, '2022-11-22', 'Super', 'Testovich');

INSERT INTO user_role (user_id, role_id)
values (1, 1);

INSERT INTO login ("method", method_value, password_required, user_id)
values ('EMAIL', 'testtest@gmail.test', true, 1);

INSERT INTO invite (invite_value, "action", created_at, expired_at, invite_attribute, invite_code, user_id)
values ('testtest@gmail.test', 'REGISTRATION', '2023-01-18', '2024-02-18', 'EMAIL', 'first-invite-value', 1);

INSERT INTO password (created_at, is_actual, password, user_id)
VALUES (now(), true, '$2a$10$LJObGm2qAI1STPp5eNRKlunJ7yppORy4BA0i0rJfTFJa76KXymQO.', 1);

INSERT INTO "role" (deleted, permission_list, role_name, description)
values (false, 'CREATE_GROUP_CHATS;VIEW_ALL_EMPLOYEES',
        'Сотрудник', 'Обычный сотрудник');

INSERT INTO "role" (deleted, permission_list, role_name, description)
values (false, 'LINE_OUTPUT;EDITING_CUSTOMER;ACCESS_DATA_CUSTOMERS',
        'Менеджер', 'Роль для работы с клиентами');

INSERT INTO "role" (deleted, permission_list, role_name, description)
values (false,
        'LINE_OUTPUT;DEPARTMENT_MODERATION;CREATE_GROUP_CHATS;ROLES_MODERATION;BAN_LIST_MODERATION;MESSAGES_TEMPLATE_MODERATION;SERVICE_REQUEST_MODERATION;REGISTRATION_EMPLOYEES;IMPORT_EMPLOYEES;EDITING_PROFILES_EMPLOYEE;VIEW_ALL_EMPLOYEES;BAN_EMPLOYEES;DELETE_EMPLOYEES;RESETTING_PASSWORD_EMPLOYEES;CHANGING_ROLES_EMPLOYEE;CHANGING_PERMISSIONS_EMPLOYEE;DEPARTMENT_MANAGEMENT_EMPLOYEES;REGISTRATION_CUSTOMER;EDITING_CUSTOMER;IMPORTING_CUSTOMERS;BAN_CUSTOMER;DELETE_CUSTOMER;AUTHORIZATION_METHOD_CUSTOMER;ACCESS_DATA_CUSTOMERS;VIEW_ALL_CUSTOMERS;VIEW_ALL_MESSAGES_CUSTOMERS;DATA_EXPORT_CUSTOMER;TECHNICAL_INFORMATION_CUSTOMERS;SCHEDULE_SETTING;CREATING_MAILING_LIST_CUSTOMERS;CREATING_MAILING_LIST_EMPLOYEES',
        'Василий', 'Все права имеющиеся на момент разворачивания');

INSERT INTO chat_type (available_permissions, chat_type_name, default_permissions)
values ('DESCRIPTION_EDIT;MEMBER_INVITE;MEMBER_PUBLIC;MESSAGE_SEND_OUT;MESSAGE_SEND_NEW;THREAD_ENABLED;HISTORY_DISABLED',
        'GROUP_CHAT', 'MESSAGE_SEND_OUT;THREAD_ENABLED;DESCRIPTION_EDIT;MEMBER_INVITE');

INSERT INTO chat_type (available_permissions, chat_type_name, default_permissions)
values ('MESSAGE_SEND_OUT;MESSAGE_SEND_NEW;THREAD_ENABLED;',
        'PRIVATE', 'THREAD_ENABLED');
