-- liquibase formatted sql

-- changeset kuchart:1669647372218-1

create table if not exists user_type
(
    id          integer generated by default as identity
        primary key,
    type_name   varchar(255) not null,
    description varchar(255) not null,
    in_use     boolean
);

alter table user_type
    owner to app_chat;
