-- liquibase formatted sql

-- changeset kuchart:1669647372218-2

create table if not exists "user"
(
    id                       integer generated by default as identity
        primary key,
    banned                   boolean not null,
    deleted                  boolean not null,
    enabled                  boolean not null,
    user_type                integer not null references "user",
    avatar_url               varchar(255),
    birth_date               timestamp,
    first_name               varchar(255),
    last_name                varchar(255),
    middle_name              varchar(255),
    extended_permission_list varchar not null
);

alter table "user"
    owner to app_chat;