-- liquibase formatted sql

-- changeset kuchart:1669647372218-5

create table if not exists invite
(
    id               integer generated by default as identity
        primary key,
    action           varchar(255) not null,
    created_at       timestamp    not null,
    expired_at       timestamp,
    invite_attribute varchar(255),
    invite_code      varchar(255),
    invite_link      varchar(255),
    invite_value     varchar(255),
    used             boolean      not null default false,
    user_id          integer      not null
        references "user"
);

alter table invite
    owner to app_chat;
