-- liquibase formatted sql

-- changeset kuchart:1669647372218-6

create table if not exists role
(
    id              integer generated by default as identity
        primary key,
    deleted         boolean      not null,
    description     varchar(255),
    permission_list varchar,
    role_name       varchar(255) not null
);

alter table role
    owner to app_chat;
