-- liquibase formatted sql

-- changeset kuchart:1669647372218-8

create table if not exists user_role
(
    id      bigint generated by default as identity
        primary key,
    role_id integer not null
        references "role",
    user_id integer not null
        references "user"
);

alter table user_role
    owner to app_chat;
